# Generated by Django 3.0.5 on 2020-07-31 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activityapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activity_periods',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tz',
        ),
    ]
