# Generated by Django 3.0.5 on 2020-07-31 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activityapi', '0002_auto_20200731_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activityapi.Timezone'),
        ),
    ]
