# Generated by Django 3.0.5 on 2020-07-31 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityapi', '0003_user_tz'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_periods',
            field=models.ManyToManyField(to='activityapi.Activity'),
        ),
    ]
